### ISSUE TITLE
Search by full thingiverse URL

### ISSUE THREAD

**Issue by ThomDietrich** [ChrisTerBeke/CuraThingiBrowserPlugin#211]
Hey there,
this might go against the idea of the plugin but I hope you can make this little change happen :)

I often browse Thingiverse in my full-blown browser, get links from friends, or stumble over something randomly. I then like to use your plugin to easily load the model into Cura. Sadly "searching" for the full URL isn't supported, reduced to the thing ID it works:

- Search for `https://www.thingiverse.com/thing:6052088` -> API error
- Search for `6052088` -> Success.

Could you please support full-URL search? Merci!

**Comment by ChrisTerBeke** [comment]
Didn't even know that searching on ID worked! It's probably part of the search functionality of the Thingiverse API. Filtering out the URL prefix would be an easy fix to implement, let me have a look.

**Comment by ChrisTerBeke** [comment]
This feature is part of [release 3.1.0 ](https://github.com/ChrisTerBeke/CuraThingiBrowserPlugin/releases/tag/v3.1.0). It should appear in the UltiMaker Marketplace soon (waiting for approval).

**Comment by ThomDietrich** [comment]
Thank you!

**Comment by ThomDietrich** [comment]
Come to think of it, there might be another improvement you could implement using a regex or similar?
What about:

* `https://www.thingiverse.com/thing:6052088/`
* `https://www.thingiverse.com/thing:6052088/files`
* `https://www.thingiverse.com/thing:6052088/files?more-stuff-here`

**Comment by ChrisTerBeke** [comment]
@ThomDietrich great suggestion, I have implemented this in PR https://github.com/ChrisTerBeke/CuraThingiBrowserPlugin/pull/217. Will be part of the next release.

Also version 3.1 is now live in the UltiMaker Marketplace.
