### ISSUE TITLE
Log in Using Google

### ISSUE THREAD

**Issue by lyte0ne** [ChrisTerBeke/CuraThingiBrowserPlugin#246]
It seems that login using Google account is not supported as there is on Facebook login option

**Comment by ChrisTerBeke** [comment]
Hi. Are you referring to the sign-in options on thingiverse.com or myminifactory.com? This plugin is not associated with either of those sites and we only redirect to the login pages that they provide. There is no Facebook (or Google) login logic in this plugin.

**Comment by lyte0ne** [comment]
Hi i mean on thingiverse.com when I install this addon and click on signin it takes me to a login page where there is no signin with google option but on the website i have this option as you can see from print screens bellow.

![image](https://github.com/ChrisTerBeke/CuraThingiBrowserPlugin/assets/5657398/c5f50952-36c6-4d02-a5d9-0d82d9fb8738)

but now I see that whatever I select it goes to the minifactory login page....

**Comment by lyte0ne** [comment]
for some reason uninstalling and installing it back now works as before....
