### ISSUE TITLE
Unable to log into Thingiverse from plugin

### ISSUE THREAD

**Issue by ccellist** [ChrisTerBeke/CuraThingiBrowserPlugin#80]
I used to be able to use this without issue but now when I load the plugin, latest version, I get the following alert: "Thingiverse indicated that you need to sign in. Please sign into your Thingiverse account and try again." I see no way to trigger a Thingiverse login anywhere. I can log into MyMiniFactory but not Thingiverse. I have tried logging in through my browser but that doesn't work either. I used to be able to just use the plugin without logging in but now it fails to show me anything but that alert.

Version of Plugin: 2.2.1
Version of Cura: 4.11.0

**Comment by lokipowers** [comment]
I'm having the same issue. I thought it was because I had changed my login details, but I'm guessing not...

**Comment by phpsystems** [comment]
+1 for this issue. Only noticed after updating Creds following thingiverse's data breach.

**Comment by BKeyport** [comment]
Same here.

**Comment by escfoe2** [comment]
Also having this issue.

**Comment by crazymikefra** [comment]
I've tried to push my request but i can't.
So, i've forked it in https://github.com/crazymikefra/ThingiBrowser
So, you can check my modifications.

Regards.

**Comment by ccellist** [comment]
@crazymikefra You should be able to make a Pull Request from your fork into this repo so that Chris can comment and hopefully approve the change.

**Comment by seafish1972** [comment]
Working now perfect again. THX.

**Comment by phpsystems** [comment]
New version from the Marketplace is working fine for me.
